### ISSUE TITLE
SSH connecting but not executing

### ISSUE THREAD

**Issue by mnino** [consolidation/Robo#326] opened 2016-05-02 02:30 UTC
Either I do not understand or the remote command isn't executing on server.  The following PHP code (hostname, IP and user renamed)...

```
class RoboFile extends \Robo\Tasks
{
        public function ls() {
                $this->taskSshExec('someserver.com', 'someuser')
                    ->remoteDir('/home/someuser')
                    ->exec('ls -la')
                    ->verbose()
                    ->run();
        }
}
```

produces the following output....

```
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/someuser/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentication succeeded (publickey).
Authenticated to someserver.com ([###.###.##.##]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending command: cd "/home/someuser"
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3160, received 2720 bytes, in 0.4 seconds
Bytes per second: sent 7682.0, received 6612.3
debug1: Exit status 0
total 1706
```

followed by a directory listing that is on the _client_ and **not** the _remote server._ I have no clue as to why. How does one obtain the output of a command executed on the remote server. Note: Remote server is Ubuntu and client is Cygwin on Win 10.

Thank you in advance  for your assistance / feedback.

Michael

**Comment by mnino-glanbia** [comment] 2016-05-02 18:41
Could anyone please offer some feedback / assistance?

**Comment by mnino-glanbia** [comment] 2016-05-05 12:00
I really need some assistance. Anyone?

**Comment by greg-1-anderson** [comment] 2016-09-13 22:59
Out of scope for this issue queue

**Comment by mnino** [comment] 2016-09-14 01:33
Please explain. What does "Out of scope" for this issue queue mean. Shouldn't you at least direct issue to another queue?

**Comment by greg-1-anderson** [comment] 2016-09-14 15:24
Sorry, I was zooming through and closing a bunch of stale issues, and at first blush, this looked like an authentication problem with your server.  I see now that was a mistake.  Are you still having trouble with this code?  I'll try to reproduce, and see if it works for me.

**Comment by greg-1-anderson** [comment] 2016-09-14 15:35
Works perfectly for me; I suspect that back in May there were some escaping issues that have since been fixed.  Be sure to upgrade to the latest dev-master of Robo, and try again.  (1.0.0 stable is imminent, and you'll want all of the latest fixes.)

If you still have problems, try `robo ls --simulate` from the directory containing your RoboFile.php; this will show you exactly what Robo is doing.  You can then copy the simulated output directly into your terminal, and see if the command Robo is generating works or not. That will help isolate whether the problem is with the command generation, or a local configuration issue.

**Closed by greg-1-anderson** 2016-09-14 15:35 UTC

**Comment by mnino** [comment] 2016-09-14 15:37
Thanks Greg. I will test on Cygwin with 1.0 when released. :-)

**Comment by greg-1-anderson** [comment] 2016-09-14 15:51
I'm pretty sure this is fixed, but in general, confirming bugfixes just *before* a release is much more useful (and expedient!) than finding out that it's still broken just *after* the release.  ;)

**Comment by mnino** [comment] 2016-09-14 15:54
Should I pull RC2?

**Comment by greg-1-anderson** [comment] 2016-09-14 16:23
@mnino I would use dev-master; it has additional fixes that RC2 does not have. I don't remember where this stuff was fixed, so best to test the latest.

**Comment by mnino** [comment] 2016-09-14 16:25
Okay, thanks. Will try this afternoon.

**Comment by mnino** [comment] 2016-09-19 15:26
We have decided to use Laravel Collective (https://laravelcollective.com/) instead but may revist in the future. Thanks for you feedback.
