### ISSUE TITLE
PHPStorm code completion broken with Packagist installs

### ISSUE THREAD

**Issue by danepowell** [consolidation/Robo#846] opened 2019-03-18 22:14 UTC
### Steps to reproduce
1. Clone a project that is built on Robo, such as [BLT](https://github.com/acquia/blt).
2. Run `composer install --prefer-source`
3. Open PHPStorm and open a file such as BLT's [src/Robo/BltTasks.php](https://github.com/acquia/blt/blob/10.x/src/Robo/BltTasks.php) or UpdateCommand.php.

### Expected behavior
Code completion should work, and no warnings should be reported regarding Robo includes.

### Actual behavior
Code completion for Robo tasks is broken (such as in BLT's [src/Robo/BltTasks.php](https://github.com/acquia/blt/blob/10.x/src/Robo/BltTasks.php)), and you get a ton of warnings: "Multiple definitions exist for class"

The root cause here appears to be that the Packagist package of Robo includes three additional files/directories that include duplicate versions of classes that PHPStorm detects:
- robotheme
- robo.phar
- robo-release.phar

Simply deleting those files fixes the errors, but that's obviously not a sustainable workaround for end users. Can those be removed from the Packagist package, or else structured in a way that PHPStorm won't scan them?

Obviously it would also help if [PHPStorm let us choose the canonical version of class files](https://youtrack.jetbrains.com/issue/WI-17646) somehow, but that doesn't seem likely to happen soon.

**Comment by greg-1-anderson** [comment] 2019-03-18 22:28
Did you try installing Robo (into your local copy of BLT) via `--prefer-source`? By default, you'll get a `dist` installation of Robo if you install a stable tag. Robo deliberately removes any sort of dev components from the dist builds, as they are only needed during development. If you are doing development, then you should install via `--prefer-soruce`.

**Comment by danepowell** [comment] 2019-03-19 01:31
Yep sorry, I should have specified that this is reproduceable using `--prefer-source`. You still get the built robo.phar, robo-release.phar, etc using `--prefer-source`.

Composer is pulling this commit for Robo 1.4.6: https://github.com/consolidation/Robo/commit/d4805a1abbc730e9a6d64ede2eba56f91a2b4eb3

It looks like you committed those build artifacts to that release, whereas in previous releases they don't exist, so this problem is specific to 1.4.6.

**Comment by greg-1-anderson** [comment] 2019-03-19 02:19
Oh I skimmed over the report too quickly. I'll look into that. Looks like artifacts from the `site` branch was committed on master, or maybe the tag was accidentally applied on the wrong branch.
\

**Comment by danepowell** [comment] 2019-03-19 03:14
Thanks. Sorry, the original report is a little misleading as I mentioned Packagist when the issue is really with GitHub.

**Comment by greg-1-anderson** [comment] 2019-03-19 15:28
Confirmed that *.phar et. al. exists in 1.4.6 but do not exist on 1.x branch. Re-released 1.4.6 as 1.4.7, and found that the release script once again added the unwanted binaries to the tag. Going to try again after fixing the release script.

**Comment by greg-1-anderson** [comment] 2019-03-19 18:54
Fixed in 1.4.9

**Closed by greg-1-anderson** 2019-03-19 18:54 UTC
