### ISSUE TITLE
https://robo.li/robo.phar is a 404

### ISSUE THREAD

**Issue by davereid-pfg** [consolidation/robo#1140] opened 2023-02-20 15:53 UTC
### Steps to reproduce
```
curl --head https://robo.li/robo.phar
HTTP/2 404
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
date: Mon, 20 Feb 2023 15:52:22 GMT
vary: Accept-Encoding
cf-ray: 79c868b4bcbcfada-SJC
server: cloudflare
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=tqo9rZ%2BhYDdPk3wrgzDI1MDwxIeLFMFGV57oCTEJ%2BIQqBJHtbmo%2F2yYDzFvogB5IPJW4c0Fxo930bG6eVTBqU1JxGuE%2BNd6aXeS4uJdF45IgzC%2BCzyeys95g"}],"group":"cf-nel","max_age":604800}
content-type: text/html; charset=utf-8
x-proxy-cache: MISS
cf-cache-status: DYNAMIC
x-github-request-id: 4330:562C:1065F8:14D6B3:63F39736
access-control-allow-origin: *
```

### Expected behavior
That it would download the .phar file correctly.

### Actual behavior
A 404 error

### System Configuration
Happening across browser, CLI, everything.

**Comment by davereid-pfg** [comment] 2023-02-20 16:44
FYI that https://github.com/consolidation/robo/releases/latest/download/robo.phar can be used as a backup

**Comment by greg-1-anderson** [comment] 2023-02-20 19:49
Effectively a duplicate of https://github.com/consolidation/robo/issues/1107, although symptoms have changed as we move closer to a solution.

**Comment by greg-1-anderson** [comment] 2023-02-20 20:20
I'd prefer long-term to use the GitHub releases as the primary means for distributing Robo phars, but note that these are out of date at the moment, until I fix up the release and publish automation.

As an interim feature, I manually placed Robo 4.0.3 at https://robo.li/robo.phar. Note that Robo 4 requires PHP 8+.

**Closed as completed by greg-1-anderson** 2023-02-20 20:20 UTC
