### ISSUE TITLE
Docs: "Edit on Github" links not working

### ISSUE THREAD

**Issue by davidsneighbour** [consolidation/robo#1132] opened 2022-12-11 14:14 UTC
Links on the documentation pages of robo.li to edit the current page (Topnavigation > Edit on Github) are not working, because the links go to the master branch, while the current live version seems to be a branch named `4.0`.

Sample (diffs bolded):

- Link on robo.li: [https://github.com/consolidation/**Robo**/edit/**master**/docs/tasks/Development.md](https://github.com/consolidation/Robo/edit/master/docs/tasks/Development.md)
- Actual Link: [https://github.com/consolidation/**robo**/edit/**4.x**/docs/tasks/Development.md](https://github.com/consolidation/robo/edit/4.x/docs/tasks/Development.md)

**Comment by amenk** [comment] 2023-02-17 11:26
Duplicate of https://github.com/consolidation/robo/issues/1110

on https://consolidation.github.io/website/ it works

**Comment by greg-1-anderson** [comment] 2023-02-18 01:45
robo.li now points at consolidation.github.io/website; however, the website is pointing at 3.x, and the latest version is 4.x. That still needs to be updated.

**Comment by greg-1-anderson** [comment] 2023-02-18 03:45
Updated to point to the 4.x branch.

**Comment by greg-1-anderson** [comment] 2023-02-18 03:48
The build gave a 500 error on GitHub; GitHub seems to be having transient problems, so perhaps this will fix itself if I rebuild later.

**Comment by greg-1-anderson** [comment] 2023-02-18 15:24
I re-ran the build, and the "Edit this page" links now point to the 4.x branch.

I have to re-enter the "robo.li" domain in the GitHub gui every time the docs build. Perhaps the domain is set in the automation, will need to look for that.

**Closed as completed by greg-1-anderson** 2023-02-18 15:24 UTC

**Comment by amenk** [comment] 2023-02-18 15:31
> I have to re-enter the "robo.li" domain in the GitHub gui every time the docs build.

Oh that's annoying 😅

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

It's supposed to create a CNAME file with the just content "robo.li" 

Maybe try adding such a file manually?

**Comment by greg-1-anderson** [comment] 2023-02-18 16:25
Oh, neat, that might work. I was planning on checking the vuepress docs, I suspect there's a domain property that I should add.

**Comment by greg-1-anderson** [comment] 2023-02-18 17:47
[vuepress docs](https://vuepress.vuejs.org/guide/deploy.html#github-pages) say to do exactly what you suggested.

**Comment by greg-1-anderson** [comment] 2023-02-18 17:54
Fixed in https://github.com/consolidation/website/commit/18567f4d6e73009c11c966b7948ffc6432285cf0

**Comment by amenk** [comment] 2023-02-18 18:35
Great :-)
