### ISSUE TITLE
Task registering is not working when using traits in the RoboFile directly

### ISSUE THREAD

**Issue by rwngallego** [consolidation/Robo#426] opened 2016-08-31 21:52 UTC
I'm trying to use the example you provide in the docs: http://robo.li/getting-started/

However I'm getting this error:

``
PHP Fatal error:  Call to undefined method RoboFile::task() in /root/robo/src/MyAssetTasks/loadTasks.php on line 13
``

Is the task() method available in the RoboFile class? According to your docs, it should: **"To use an external task, ensure that its class files are available (e.g. require its project in your composer.json file), and include corresponding trait or traits in your Robofile."**

````
<?php
class RoboFile extends \Robo\Tasks
{
    use \MyAssetTasks\loadTasks;

    public function build()
    {
        $this->taskCompileAssets('web/css-src')
            ->to('web/assets.min.css')
            ->run();
    }
}
?>
````

**Comment by greg-1-anderson** [comment] 2016-08-31 23:28
The documentation on robl.li is still reflecting the 0.x version of Robo, since 1.x has not had its first stable release yet.  That should happen soon, though, at which point this issue should straighten itself out.

All the same, what you have quoted above still looks basically accurate.  Here's an example of a [Robo extension's loadTasks method](https://github.com/boedah/robo-drush/pull/3/files#diff-dcab1320182d8d706533739547ee063dR13).  The PR for the updated documentation for Robo 1.0 is https://github.com/consolidation-org/Robo/pull/415.

**Comment by rwngallego** [comment] 2016-09-02 04:22
I'm installing the RC3 version and getting this next output twice:

````
php robo.phar --version
Robo version 1.0.0-RC3
Robo version 1.0.0-RC3
````

**Comment by greg-1-anderson** [comment] 2016-09-02 04:36
Only prints once for me.  MacOS, php 7.0.10.

Also, I presume since you are using dev-master (which currently reports 1.0.0-RC3), that you built your own phar with Robo.

**Comment by rwngallego** [comment] 2016-09-02 04:37
Trying to install it with global require throws the following error:
````
composer global require codegyre/robo
Changed current directory to /root/.composer
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^0.7.2 for codegyre/robo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for codegyre/robo ^0.7.2 -> satisfiable by codegyre/robo[0.7.2].
    - Conclusion: remove symfony/event-dispatcher v3.1.3
    - Conclusion: don't install symfony/event-dispatcher v3.1.3
    - codegyre/robo 0.7.2 requires henrikbjorn/lurker ~1.0 -> satisfiable by henrikbjorn/lurker[1.0.0, 1.1.0].
    - henrikbjorn/lurker 1.0.0 requires symfony/event-dispatcher ~2.2 -> satisfiable by symfony/event-dispatcher[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - henrikbjorn/lurker 1.1.0 requires symfony/event-dispatcher ~2.2 -> satisfiable by symfony/event-dispatcher[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Can only install one of: symfony/event-dispatcher[v2.7.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.11, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.12, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.13, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.14, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.15, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.16, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.17, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.11, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.11, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.12, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.13, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.14, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.15, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.16, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.17, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.18, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.19, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.20, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.21, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.22, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.23, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.24, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.25, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.26, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.27, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.28, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.29, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.30, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.31, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.32, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.33, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.34, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.35, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.36, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.37, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.38, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.39, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.40, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.41, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.42, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.11, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.12, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.11, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.12, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.13, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.6.9, v3.1.3].
    - Installation request for symfony/event-dispatcher (locked at v3.1.3) -> satisfiable by symfony/event-dispatcher[v3.1.3].


Installation failed, reverting ./composer.json to its original content.
````

**Comment by greg-1-anderson** [comment] 2016-09-02 04:39
`composer global require` can produce extremely unpredictable results depending on what else you have installed.  Try [cgr](https://github.com/consolidation-org/cgr) instead.

**Comment by rwngallego** [comment] 2016-09-02 04:41
Ok, I'll take a look at cgr. Regarding the .phar, this is the file that I get when following your installation guides:

````
Download robo.phar >
wget http://robo.li/robo.phar
````

**Comment by greg-1-anderson** [comment] 2016-09-02 05:00
I tried a fresh download, and was able to reproduce the double-version problem.  Robo prints its version number if there is no RoboFile.php at the current working directory.  Run `./robo.phar init` to create a RoboFile, and the double-version output will go away.

I'm not sure why the version up for download is reporting 1.0.0-RC3; it should be RC2.

**Comment by pingers** [comment] 2016-09-05 12:57
@greg-1-anderson because there was a version bump committed to master... and it looks like the build went from master for some reason, instead of the tag.

**Comment by greg-1-anderson** [comment] 2016-09-05 13:40
The current convention for Robo is for the master branch to report the next version that would be tagged. It would probably be better for it to report something like 1.0.0-RC3-dev, but the fact that master is 1.0.0-RC3 is, at least for now, normal. The mystery is how master was published as the downloadable robo.phar in place of 1.0.0-RC2. This probably happened because someone accidentally ran the publish script -- could have even been me.

**Closed** 2016-09-13 22:55 UTC
